/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visao;

import Logico.Avaliacao;
import Logico.EncriptaSenha;
import Logico.Usuario;
import dao.DaoAvaliacao;
import dao.DaoUsuario;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUSTAVO
 */
public class TelaAvaliacao extends javax.swing.JDialog {

    /**
     * Creates new form TelaAvaliacao
     */
    DefaultTableModel tmAvaliacao = new DefaultTableModel(null, new String[] {"Código","Descrição"});
    List lista;
    ListSelectionModel lsmAvaliacao;
    
    public TelaAvaliacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        confTela(parent);
    }
    
    private void confTela(java.awt.Frame parent) {
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPesquisa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTPesquisa = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabela = new javax.swing.JTable();
        jPFicha = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTIdAvaliacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTPesoInicial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDtInicial = new com.toedter.calendar.JDateChooser();
        jDtFinal = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTCodUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAObservacao = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTAltura = new javax.swing.JTextField();
        jTPesoPlanejado = new javax.swing.JTextField();
        jTNome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTPesoFinal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTObjetivo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBIncluir = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBSalvar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jBPrimeiro = new javax.swing.JButton();
        jBAnterior = new javax.swing.JButton();
        jBProximo = new javax.swing.JButton();
        jBUltimo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Avaliação- SIGAF");

        jPPesquisa.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/clientes.png"))); // NOI18N
        jLabel1.setText("Avaliação Físicas");

        jTPesquisa.setToolTipText("Para pesquisar digite um Nome e aperte Enter");
        jTPesquisa.setPreferredSize(new java.awt.Dimension(59, 27));
        jTPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTPesquisaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPPesquisaLayout = new javax.swing.GroupLayout(jPPesquisa);
        jPPesquisa.setLayout(jPPesquisaLayout);
        jPPesquisaLayout.setHorizontalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPPesquisaLayout.setVerticalGroup(
            jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPesquisaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTTabela.setModel(tmAvaliacao);
        jTTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTabela);
        jTTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmAvaliacao = jTTabela.getSelectionModel();
        lsmAvaliacao.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e){
                if (! e.getValueIsAdjusting()){
                    //jTTabelaMouseClicked(e);
                    tabelaLinhaSelecionada(jTTabela);
                    jTabbedPane1.setSelectedIndex(1);}}
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista", jPanel3);

        jLabel2.setText("Código:");

        jTIdAvaliacao.setEnabled(false);

        jLabel3.setText("Peso Inicial:");

        jTPesoInicial.setEnabled(false);

        jLabel4.setText("Data Inicial:");

        jLabel5.setText("Data Final:");

        jDtInicial.setEnabled(false);

        jDtFinal.setEnabled(false);

        jLabel6.setText("Peso Planejado:");

        jLabel7.setText("Código Usuário:");

        jTCodUsuario.setEnabled(false);
        jTCodUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCodUsuarioKeyPressed(evt);
            }
        });

        jLabel8.setText("Nome:");

        jLabel9.setText("Observação:");

        jTAObservacao.setColumns(20);
        jTAObservacao.setRows(5);
        jTAObservacao.setEnabled(false);
        jScrollPane3.setViewportView(jTAObservacao);

        jLabel10.setText("Altura:");

        jTAltura.setEnabled(false);

        jTPesoPlanejado.setEnabled(false);

        jTNome.setEnabled(false);

        jLabel11.setText("Peso Final:");

        jTPesoFinal.setEnabled(false);

        jLabel12.setText("Objetivo:");

        jTObjetivo.setEnabled(false);

        javax.swing.GroupLayout jPFichaLayout = new javax.swing.GroupLayout(jPFicha);
        jPFicha.setLayout(jPFichaLayout);
        jPFichaLayout.setHorizontalGroup(
            jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFichaLayout.createSequentialGroup()
                        .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPFichaLayout.createSequentialGroup()
                        .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jTIdAvaliacao, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jTPesoInicial))
                        .addGap(51, 51, 51)
                        .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTPesoPlanejado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPFichaLayout.createSequentialGroup()
                                .addComponent(jTPesoFinal)
                                .addGap(18, 18, 18))))
                    .addGroup(jPFichaLayout.createSequentialGroup()
                        .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTCodUsuario))
                        .addGap(38, 38, 38)
                        .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(jPFichaLayout.createSequentialGroup()
                        .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPFichaLayout.createSequentialGroup()
                                .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(117, 117, 117))))
        );
        jPFichaLayout.setVerticalGroup(
            jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFichaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTIdAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPesoPlanejado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPesoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ficha", jPFicha);

        jBIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/add.png"))); // NOI18N
        jBIncluir.setText("Incluir");
        jBIncluir.setPreferredSize(new java.awt.Dimension(81, 24));
        jBIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIncluirActionPerformed(evt);
            }
        });

        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/edit.png"))); // NOI18N
        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/save.png"))); // NOI18N
        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/cancel.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 102, 255));

        jBPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/first.png"))); // NOI18N
        jBPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrimeiroActionPerformed(evt);
            }
        });

        jBAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/previous.png"))); // NOI18N
        jBAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnteriorActionPerformed(evt);
            }
        });

        jBProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/next.png"))); // NOI18N
        jBProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProximoActionPerformed(evt);
            }
        });

        jBUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/last.png"))); // NOI18N
        jBUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jBAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jBProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jBUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPesquisaKeyPressed
        //PESQUISA USUARIO

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ListarAvaliacao();
        }
    }//GEN-LAST:event_jTPesquisaKeyPressed

    private void jTTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            jTabbedPane1.setSelectedIndex(1);
            tabelaLinhaSelecionada(jTTabela);
            //jTabbedPane1.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jTTabelaMouseClicked

    private void jBIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIncluirActionPerformed
        //Inclusao de novo usuario
        
        BotaoAcaoAv bt = new BotaoAcaoAv(this);
        bt.AtivaCampos();
        jTIdAvaliacao.setEnabled(false);
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_jBIncluirActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        //Edita os dados do Usuario
        BotaoAcaoAv bt = new BotaoAcaoAv(this);
        bt.AtivaCampos();
        bt.setEdicao();
        jTIdAvaliacao.setEnabled(false);
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // Grava os dados da Avaliacao
        Avaliacao avaliacao = new Avaliacao();
        DaoAvaliacao dao = new DaoAvaliacao();
        BotaoAcaoAv bt = new BotaoAcaoAv(this);
        if (jTIdAvaliacao.getText().equals("")) {
            avaliacao.setDataInicial(jDtInicial.getDate());
            avaliacao.setPesoInicial(Float.valueOf(jTPesoInicial.getText()));
            avaliacao.setAltura(Float.valueOf(jTAltura.getText()));
            avaliacao.setPesoAlcancado(Float.valueOf(jTPesoPlanejado.getText()));
            avaliacao.setDataFinal(jDtFinal.getDate());
            avaliacao.setObservacao(jTAObservacao.getText());
            avaliacao.setPesoFinal(Float.valueOf(jTPesoFinal.getText()));
            avaliacao.setObjetivo(jTObjetivo.getText());
            avaliacao.setIdUsuario(Integer.valueOf(jTCodUsuario.getText()));
            avaliacao.setPesoPlanejado(Float.valueOf(jTPesoPlanejado.getText()));

            try {
                dao.incluir(avaliacao);
                JOptionPane.showMessageDialog(null, "Avaliação cadastrada com sucesso!", "Confirmação!", 1);
                bt.LimpaCampos();
                bt.setNavegacao();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao gravar dados!", "Atenção!", 1);
                System.out.println("Gravacao de Avaliação " + ex);
                bt.LimpaCampos();
                bt.setNavegacao();
                Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            System.out.println("passou aqui");
            AlteraAvaliacao();
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // Cancela ação da Avaliacao
        BotaoAcaoAv bt = new BotaoAcaoAv(this);
        bt.DesativaCampos();
        bt.LimpaCampos();
        bt.setNavegacao();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrimeiroActionPerformed
        // TODO add your handling code here:
        selecionarLinhaTabela(0);

    }//GEN-LAST:event_jBPrimeiroActionPerformed

    private void jBAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnteriorActionPerformed
        // TODO add your handling code here:
        int quantLinha = jTTabela.getSelectedRow();
        selecionarLinhaTabela(quantLinha-1);
    }//GEN-LAST:event_jBAnteriorActionPerformed

    private void jBProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProximoActionPerformed
        // TODO add your handling code here:
        int quantLinha = jTTabela.getSelectedRow();
        selecionarLinhaTabela(quantLinha+1);
    }//GEN-LAST:event_jBProximoActionPerformed

    private void jBUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUltimoActionPerformed
        // TODO add your handling code here:
        int quantLinha = jTTabela.getRowCount();
        selecionarLinhaTabela(quantLinha-1);

    }//GEN-LAST:event_jBUltimoActionPerformed

    private void jTCodUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCodUsuarioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Usuario usuario = new Usuario();
            DaoUsuario dao = new DaoUsuario();
            String pesquisa =jTCodUsuario.getText();
            //usuario.setNome(pesquisa);
            
            usuario.setIdusuario(Integer.parseInt(pesquisa));
            try {
                lista = dao.pesquisarUsuario(usuario);
                MostraListaUse(lista);
                //jTNome.setText(lista.get(usuario.getNome()));
                //jTCodUsuario.setText(String.valueOf(lista.get(usuario.getIdusuario())));
                
            } catch (SQLException ex) {
                Logger.getLogger(TelaAvaliacao.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_jTCodUsuarioKeyPressed

    public void MostraListaUse(List<Usuario> usuario){
        for(int i=0; i< usuario.size(); i++){
            jTCodUsuario.setText(String.valueOf(usuario.get(i).getIdusuario()));
            jTNome.setText(usuario.get(i).getNome());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAvaliacao dialog = new TelaAvaliacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
       public void AlteraAvaliacao() {
       /* Usuario usuario = new Usuario();
        BotaoAcao bt = new BotaoAcao(this);
       if(jTTabela.getSelectedRow()!= -1){
        usuario.setNome(jTPesoInicial.getText());
        usuario.setDtcadastro(jDtInicial.getDate());
        usuario.setDtnascimento(jDtFinal.getDate());
        usuario.setEmail(jTCodUsuario.getText());
        usuario.setObservacao(jTAObservacao.getText());
        usuario.setSenha(EncriptaSenha.encripta(new String(jPSenha.getPassword())));     
        usuario.setSexo((String) jCSexo.getSelectedItem());
        if (jChAtivo.isSelected()) {
            usuario.setEstado(true);
        } else {
            usuario.setEstado(false);
        }
        
        try {
            DaoUsuario dao = new DaoUsuario();
            dao.editar(usuario);
            JOptionPane.showMessageDialog(null, "Registro editado com sucesso!", "Confirmação!", 1);
            bt.LimpaCampos();
            bt.setNavegacao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados!", "Atenção!", 0);
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            bt.LimpaCampos();
            bt.setEdicao();
            bt.setNavegacao();

        }
       }*/

    }

    public void ListarAvaliacao() {
        DaoUsuario dao = new DaoUsuario();
        Usuario usuario = new Usuario();

        String pesquisa = "%" + jTPesquisa.getText() + "%";
        usuario.setNome(pesquisa);
        try {
            lista = dao.pesquisar(usuario);
            MostraPesquisa(lista);
        } catch (SQLException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void MostraPesquisa(List<Usuario> usuario) {
        while (tmAvaliacao.getRowCount() > 0) {
            tmAvaliacao.removeRow(0);
        }
        if (!usuario.isEmpty()) {
            String[] linha = new String[]{null, null};
            for (int i = 0; i < usuario.size(); i++) {
                tmAvaliacao.addRow(linha);
                tmAvaliacao.setValueAt(usuario.get(i).getNome(), i, 0);
                tmAvaliacao.setValueAt(usuario.get(i).getEmail(), i, 1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não cadastrado!", "Atenção!", 0);
        }

    }
    
       private void selecionarLinhaTabela(int posicao) {
        int quantidadeLinhas = this.jTTabela.getRowCount();
        if ((posicao >= 0) && (posicao < quantidadeLinhas)) {
           this.jTTabela.requestFocus();
           this.jTTabela.clearSelection();
            this.jTTabela.addRowSelectionInterval(posicao, posicao);
        }
     }

    public void tabelaLinhaSelecionada(JTable tabela) {
        /*BotaoAcao bt = new BotaoAcao(this);
        if (jTTabela.getSelectedRow() != -1) {
            jTIdusuario.setText(String.valueOf(lista.get(tabela.getSelectedRow()).getIdusuario()));
            jTPesoInicial.setText(lista.get(tabela.getSelectedRow()).getNome());
            jTCodUsuario.setText(lista.get(tabela.getSelectedRow()).getEmail());
            jTAObservacao.setText(lista.get(tabela.getSelectedRow()).getObservacao());
            jPSenha.setText(lista.get(tabela.getSelectedRow()).getSenha());
            jCSexo.setSelectedItem(lista.get(tabela.getSelectedRow()).getSexo());
            jChAtivo.setSelected(lista.get(tabela.getSelectedRow()).isEstado());
            jDtInicial.setDate(lista.get(tabela.getSelectedRow()).getDtcadastro());
            jDtFinal.setDate(lista.get(tabela.getSelectedRow()).getDtnascimento());

            bt.setNavegacao();
        } else {
            bt.LimpaCampos();
        }
                */

    }

    public javax.swing.JButton getjBCancelar() {
        return jBCancelar;
    }

    public javax.swing.JButton getjBEditar() {
        return jBEditar;
    }

    public javax.swing.JButton getjBIncluir() {
        return jBIncluir;
    }

    public javax.swing.JButton getjBSalvar() {
        return jBSalvar;
    }

    public javax.swing.JButton getjBPrimeiro() {
        return jBPrimeiro;
    }

    public javax.swing.JButton getjBProximo() {
        return jBProximo;
    }

    public javax.swing.JButton getjBUltimo() {
        return jBUltimo;
    }

    public javax.swing.JButton getjBAnterior() {
        return jBAnterior;
    }

     public com.toedter.calendar.JDateChooser getjDtCadastro() {
        return jDtInicial;
    }

    public com.toedter.calendar.JDateChooser getjDtNascimento() {
        return jDtFinal;
    }

    public javax.swing.JTextField getjTEmail() {
        return jTCodUsuario;
    }

    public javax.swing.JTextField getjTIdusuario() {
        return jTIdAvaliacao;
    }

    public javax.swing.JTextField getjTNome() {
        return jTPesoInicial;
    }

    public javax.swing.JTextArea getjTAObservacao() {
        return jTAObservacao;
    }

    public javax.swing.JPanel getjPFicha() {
        return jPFicha;
    }

    public javax.swing.JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public javax.swing.JTable getjTTabela() {
        return jTTabela;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBIncluir;
    private javax.swing.JButton jBPrimeiro;
    private javax.swing.JButton jBProximo;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBUltimo;
    private com.toedter.calendar.JDateChooser jDtFinal;
    private com.toedter.calendar.JDateChooser jDtInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPFicha;
    private javax.swing.JPanel jPPesquisa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAObservacao;
    private javax.swing.JTextField jTAltura;
    private javax.swing.JTextField jTCodUsuario;
    private javax.swing.JTextField jTIdAvaliacao;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTObjetivo;
    private javax.swing.JTextField jTPesoFinal;
    private javax.swing.JTextField jTPesoInicial;
    private javax.swing.JTextField jTPesoPlanejado;
    private javax.swing.JTextField jTPesquisa;
    private javax.swing.JTable jTTabela;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
